name: '微信定时推送任务'
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set execute permission
        run: chmod +x ./weixin.exe
      - name: Run weixin.exe
        run: ./weixin.exe
